### ISSUE TITLE
ffprobe missing in Windows bundle

### ISSUE THREAD

**Issue by kevanbrown** [mhogomchungu/media-downloader#103]
Media Downloader Version: 2.2.1
OS: Windows 11 x64
Package: Portable

ffprobe appears to be missing from the bundled version of ffmpeg.  ffprobe not found errors are thrown in the log when the post processing task runs.  If ffprobe will not be included in the bundled version of ffmpeg, what is the supported way to update/stage a new version of ffmpeg that includes ffprobe, as well as what is the latest supported version for use with Media Downloader/yt-dlp?

**Comment by mhogomchungu** [comment]
I will look into adding ffprobe in the next release.

1. Go to Media Downloader folder and then go to "3rdParty" subfolder and delete the folder that start with "ffmpeg".
2.  Go to here[1] and download a version that works for you, extract it and place the extracted folder in the 3rdParty folder.
3. Restart Media Downloader and it should pick up your version that has ffprobe.

[1] https://github.com/yt-dlp/FFmpeg-Builds/releases/tag/latest

**Comment by kevanbrown** [comment]
This is what I had assumed, but I wanted to check with you first since you perform a version check for ffmpeg every time Media Downloader is launched.

As far as branch; is should I stick with the 4.x branch (which you currently bundle) or go with the 5.x branch?  Or does it matter?

**Comment by mhogomchungu** [comment]
1. Go with 5.x. 

2. The developer of yt-dlp said the 5.x series does not offer any advantages over 4.x series.

3. I will release the next version on April 1st, 2022 and it will come bundled with both ffmpeg and ffprobe. The reason i do not bundle ffprobe is because i did not think it was needed and the statically build binaries are massive and i wanted to reduce the size of the installer. I will use the shared version next time since each executable does not take much space and hence adding ffprobe will essentially be free.

**Comment by kevanbrown** [comment]
Excellent.  Thanks!

**Comment by mhogomchungu** [comment]
New release is out and ffprobe is now included.

https://github.com/mhogomchungu/media-downloader/releases/tag/2.3.0
