### ISSUE TITLE
Add a subscription refresh buttonn

### ISSUE THREAD

**Issue by J3Rik0** [mhogomchungu/media-downloader#105]
I've downloaded a playlist before changing the naming format, so the videos couldn't be sorted in any way. I've deleted the files, pasted the playlist link again and after hitting Get List, it only said Downloading video info 2 of 173 and stop, all the buttons active again, but didn't do anything else.

I've just cleared the subscriptions_archive_file.txt and it works again. Also the file is kinda hidden, and it's not really obvious what it does from it's name, or if it's used since it's an archive.

Please make a button to clear that file from the UI.

Thanks a bunch for this great tool

**Comment by mhogomchungu** [comment]
Please the second and third option from this[1] entry in the FAQ. It could have worked without clearing the archive file if you removed the "--break-on-existing" option is the "Get List Options" field.

The presence of this hidden archive file does not sit well with me because it stores data on disk without user's consent but its necessary for the subscription feature to work "out of the box". yt-dlp and youtube-dl have an option "--download-archive" that sets the archive file and Media Downloader uses this option if it is set and uses its hidden file if it is not.

I am still thinking about to best support this hidden archive file and that for the suggestion.

[1] https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#6-what-are-commonly-used-options-in-the-get-list-options-in-the-playlist-tab

**Comment by candrapersada** [comment]
kenapa tidak bisa menggunakan `Enter a text you want to be seen in the Ui in the "Ui Name" text field.` and `Enter a subscription url in the "Url" text field.`
![image](https://user-images.githubusercontent.com/36833664/178867167-d0621a14-c9d3-42da-9850-96a7611c900d.png)

**Comment by mhogomchungu** [comment]
Done.

There is now a button to clear the internal archive file and a checkbox to enable/disable it.

![Screenshot_20220929_095149](https://user-images.githubusercontent.com/3496115/192960214-00cd5f0a-1d50-400d-a748-9946d7e53dfa.png)
![Screenshot_20220929_095210](https://user-images.githubusercontent.com/3496115/192960242-95aab711-4593-4fd7-a0ed-f1b902c4fe27.png)
