### ISSUE TITLE
Auto save not downloaded media on exit.

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#121]
Sorry, but i didn't understand this option : " Add an option to auto save not downloaded media on exit."

if we cancel a download, Media-Downloader keeps the downloaded part of the canceled file?

**Comment by mhogomchungu** [comment]
Do not set the option, add a bunch of Urls in batch downloader tab and then restart and all the link you added will be gone.

Set the option, add a bunch of Urls in batch downloader tab and then restart and the Urls you added will be there and will be the way you left them. 

Media Downloader does not do the actual downloading and hence it does not keep the downloaded ,part file, yt-dlp is the one that is doing the actual downloading and it is the one that leaves behind the .part file so that it can continue downloading where it left off when the downloading is restarted.

The feature of Media Downloader remembering Urls of media that are yet to complete and yt-dlp keeping .part files of incomplete downloads makes it easy to add a list of Urls to download and then download a few, shut down the program and then restart it later on to continue with downloading.
