### ISSUE TITLE
Video qualities

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#128]
Hello, this video from mail. ru has two video quality: 240 p and 720p, I was able to download it by choosing the preset "default", but it downloaded me the HD video which has a very large size, can Media-Downloader add a preset to show us the available video quality so that we can choose the desired video quality we want to download please ?

https://my.mail.ru/v/thisishorosho_tv/video/22/1249.html

**Comment by mhogomchungu** [comment]
The preset options that are added by default are for youtube only because they are known in advance and there is no need to waste time and data to keep refetching it on every link added.

If you want to know available options from youtube or any other website, the do the following:-

1. When using basic downloader

- Add the link to the Url text field,
- Click "Get List" button.
- Wait for yt-dlp to get a list of available options and it will display them if successful.
- Click the one you want from the generated list.
- Click download to download it.

2. When using batch downloader tab
-  Enter Url in the Url text field.
-  Right click the entry and then select "Show Media Options"
- Wait for yt-dlp to fetch available options and it will display them if successful.
- Click the one you want and then click "Set". 
- Click download to download it.

With both method above, you can select multple options by first holding CTRL key and then click the option you want. For example, i always use 242+250 options when downloding youtube videos so i would first hold the CTRL key and then click 242 entry followed by 250 entry.

If it is a website you regulary download media from and from experience you know the format code does not change then you can add it to the preset list for easier access and save yourself the hassle of asking for the info you already know everytime.

**Comment by trimechee** [comment]
Great ! Thank you very much ! 

Even when i have only one video downloader, i prefer to use batch downloader because its graphical interface is more nice and clear and colorful, because in basic downloader, i don't even know if the download is finished, but select do Right click the entry and then select "Show Media Options" each time is a bit boring and tiring, can you add the ""Get List" button to batch donwloader for more simplicity and speed, thank you very much!

**Comment by mhogomchungu** [comment]
If i add all the buttons you ask, somebody else will complain of too many buttons that add clutter and overwhelm noobs.
