### ISSUE TITLE
New components

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#137]
Hello, I often watch French tv but apparently, yt-dlp can't download replays of some tv shows from some French tv websites, so interanutes have invented new tools to download French replays, but it seems complicated to use for beginners , it will be awesome if our beloved Media-Downloader can integrate these tools! :

https://github.com/simulot/aspiratv

https://github.com/Unrud/video-downloader

https://forum.ubuntu-fr.org/viewtopic.php?id=1559861

https://doc.ubuntu-fr.org/dpluzz

https://forum.ubuntu-fr.org/viewtopic.php?id=2029338

**Comment by mhogomchungu** [comment]
1. Unrud video downloader is a GUI tool and can not be supported.
2. aspiratv looks like its no longer maintained because last commit is more than a year ago.
3. dpluzz+ seems like a ubuntu specific thing i could not see where they are hosting the code and how i can download it when i am not using ubuntu.

All these tools do not seem fit for support.

**Comment by trimechee** [comment]
Thank you very much for having had the kindness and EFFORTto examine these softwares, there is no problem, already Media-Downloader downloads from many sites, it is already very  extraordinary :)
