### ISSUE TITLE
 Internal web browser to download without extension 

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#138]
Hello , I asked FireDM developers if there is a possibility to download videos without need to install addo extensions in web browser like videodownoadhelper, because yt-dlp can't detect all embedded videos in streaming websites like on this site:

https://wiflix.city/serie-en-streaming/22439-fear-the-walking-dead-saison-7.html

so we have to install a video extension that detects embed video links then we pass the link in the download manager.....the developer told me it's possible and that he tried and it worked and that FireDM can internally parse the webpage and extract all the hidden links, i.e. he was able to embed some sort of browser inside FireDM but it's not for the average user but I convinced him to put this project in public because the video extensions are often paid, or include ads and viruses and he agreed to put an experimental version of FireDM by integrating webdriver chromedriver and selenium  or cirlink ......  sadly i do not remember the name of the programs he used and unfortunately the FireDM repsitory was removed recently so I can't find this experimental version anymore.....

it will be great if our great beloved Media-Dwonloader can integrate an internal minimal web browser to analyze all streaming embed links that yt-dlp cannot detect and thus do without the use of video extensions and addons like videodownloadhelper, thank you very much !

**Comment by mhogomchungu** [comment]
You do not need a web browser and all you need is a parser that takes a web URL and then go through it to discover media URL to download.

This is not an easy task because there are a whole lot of websites out there and its simply not possible to support them all and even the ones that are supported break all the time and they constantly need to be reworked.

This is a task best suited to dedicated tools that deal with this kind of thing like yt-dlp and open a website support request if it is not supported yet.

**Comment by trimechee** [comment]
Interesting, thank you very much :) i have found these last weeks many open source extension taht detect video streaming, so i'm confident lol
