### ISSUE TITLE
Ununtu arm64

### ISSUE THREAD

**Issue by arjung24** [mhogomchungu/media-downloader#145]
Where is package for arm64 based ubuntu??

**Comment by mhogomchungu** [comment]
https://software.opensuse.org//download.html?project=home%3Aobs_mhogomchungu&package=media-downloader

1. Click Ubuntu icon on the page from the above link.

2. Select "grab packages directly" and then select the package that is
applicable to your version of Ubuntu to download it.

3. I hope you know how to install debian binary packages.

**Comment by arjung24** [comment]
But my system is arm64 which is not available in this list

**Comment by arjung24** [comment]
All are amd64 and i386

**Comment by mhogomchungu** [comment]
There are no packages for arm64 because opensuse build system does not support them.

A full list of supported architechures is here[1] and the full list of the ones that are availabe for each distribution is here[2]

[1] https://build.opensuse.org/repositories/home:obs_mhogomchungu/media-downloader

[2] https://build.opensuse.org/package/show/home:obs_mhogomchungu/media-downloader
