### ISSUE TITLE
svtplay-dl

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#150]
Hello, it will be great to add support for this command-line program : svtplay-dl : 

https://svtplay-dl.se/

https://gitlab.com/posktomten/streamcapture2/-/wikis/home

**Comment by trimechee** [comment]
Interesting, thank you a lot for these clarifications ans trying to integrate this program! for the moment this program seems to focus only on downloading Swedish and Dutch sites, it is not so necessary to integrate it, I thought it supports youtube but apparently not, if the program supports one day the download from youtube, rutube... there it might be useful to integrate it ....

**Comment by mhogomchungu** [comment]
Found the solution to the problem when i reported the issue

https://github.com/spaam/svtplay-dl/issues/1484

**Comment by trimechee** [comment]
Wonderful ! thank you very much !

**Comment by mhogomchungu** [comment]
Support for this program is already in. 

Current thinking as of right now says users of this backend will have to manually install its binary because they are not hosted at github and i do not want to have another way of downloading binaries.

![Screenshot_20220617_172210](https://user-images.githubusercontent.com/3496115/174319737-8ef36be4-9bd7-413d-ba0f-0d3036f8e639.png)
![Screenshot_20220617_172426](https://user-images.githubusercontent.com/3496115/174319745-929cdb62-2298-4488-9e25-29e02ac7d3ef.png)
![Screenshot_20220617_172534](https://user-images.githubusercontent.com/3496115/174319747-14b61bdc-2b8c-4481-b971-d0749313d09d.png)

**Comment by trimechee** [comment]
Excellent ! thank you so much 🥇  youtube-dl can encounter bugs and even was banned from github because it allowed downloading protected content, so it's good to have another program in reserve, I think I'll ask the developer of svtplay to add support for other sites from other countries and support for streaming sites and platforms....

Thank you again for integrating this program with the wonderful Media-Downloader :)
