### ISSUE TITLE
Wget fails to download in batch downloader

### ISSUE THREAD

**Issue by SilverKnight-Z** [mhogomchungu/media-downloader#176]
When I try to download files from from a list of links in a text file using media downloader's batch downloader, wget fails to download all of them (except for the last one for some odd reason).

![media-down-fail](https://user-images.githubusercontent.com/82909608/188330923-0085d72a-0dba-49eb-bd13-b5356b0b0cb4.jpg)

I tried using "-c" and "-i" options but still fails. I also tried downloading a single link with wget in the basic donwloader and it worked perfectly. Then, I tried to donwload using commands in the wget.exe file, and it downloaded everything without any problem.

I'm I doing something wrong? Is it something missing? Or Is this a bug?

**System information:**
- Windows 7 Starter Service Pack 1 32-bit
- Media Downloader 2.5.0 portable
- wget extension installed
- yt-dlp_x86 2022.09.01
- wget 1.21.3

**Comment by mhogomchungu** [comment]
From where did you get wget on windows?

Everything works as expected on Linux.

**Comment by SilverKnight-Z** [comment]
I got it from here: https://eternallybored.org/misc/wget/releases/wget-1.21.3-win32.zip

**Comment by mhogomchungu** [comment]
Could you post links to those images you want to download, i would to test them locally because i can not reproduce this.

**Comment by SilverKnight-Z** [comment]
Here you have the links. I put them in a text file so you can load it in media downloader like I did (I just noticed that I forgot to mention it in the original post). I also added a few more links to test, and it just downloaded from links 9, 10 and 13. I tested all links in brave browser before download and all of them work.

I made the text file using Notepad++ 8.4.4

[Image links.txt](https://github.com/mhogomchungu/media-downloader/files/9658346/Image.links.txt)

**Comment by mhogomchungu** [comment]
I found the problem and its [here](https://github.com/mhogomchungu/media-downloader/blob/7f3da6bccad8006f4904848f112813a0bdaecb6d/src/batchdownloader.cpp#L1297) and the solution i am going with is to replace "\r\n" with "\n" before doing the splitting and the code is [here.](https://github.com/mhogomchungu/media-downloader/blob/7f3da6bccad8006f4904848f112813a0bdaecb6d/src/batchdownloader.cpp#L1293)

The text editor you are using uses "\r\n" character sequence to put text into different lines while the code expects "\n" character sequence and the end result with your text file is all url ending up with '\r' character as a last character in each url and getting the url fails because no such url exist.

The last one works because the "\r\n" character sequence is not there after the url.

Had to use a hex editor to see this because '\r' character is not visible in the UI.

![Screenshot_20220928_094349-1](https://user-images.githubusercontent.com/3496115/192708411-c8443bf1-da4b-498c-9432-9e5eee5479c0.png)

**Comment by mhogomchungu** [comment]
New version is out and it has a fix for this issue: https://github.com/mhogomchungu/media-downloader/releases/tag/2.6.0

**Comment by SilverKnight-Z** [comment]
> 
> New version is out and it has a fix for this issue: https://github.com/mhogomchungu/media-downloader/releases/tag/2.6.0

Awesome! Thank you for your Hard work!
