### ISSUE TITLE
ability to have profiles for downloading options in download tab

### ISSUE THREAD

**Issue by candrapersada** [mhogomchungu/media-downloader#184]
why is there no ability to have profiles in `Basic download tab` `Batch downloader tab` and `Playlist downloader tab`?

**Comment by mhogomchungu** [comment]
I think it is betters to ask for a feature if you want it and not ask why it does not exist yet.

The ability does not exist because i have no need for it and no body asked for it.

It also takes time and effort to:-
1. Design the UI that supports a feature.
2. Write code that implements the feature.
3. Maintain the written code and make sure it always works as expected.

**Comment by mhogomchungu** [comment]
Done

![Screenshot_20221014_153148](https://user-images.githubusercontent.com/3496115/195848118-4106b301-a4c8-48c5-a0db-b713e1f1249e.png)
![Screenshot_20221014_153207](https://user-images.githubusercontent.com/3496115/195848130-264bdb94-8552-450f-ae6e-3d99e7ce05ec.png)

**Comment by candrapersada** [comment]
how to set download options + preset?
![image](https://user-images.githubusercontent.com/36833664/196051317-00d59a9b-bdce-4f7b-a3a8-a9121bb5f37e.png)
![image](https://user-images.githubusercontent.com/36833664/196051284-d76b8104-112d-4e59-8203-5d0e6c7c94e1.png)

**Comment by mhogomchungu** [comment]
Its now possible with the git version
