### ISSUE TITLE
Update readme to include info of how to use plugins together in combination

### ISSUE THREAD

**Issue by formlessdao** [mhogomchungu/media-downloader#218]
Hi, you include plugins that fulfill a similar function.
It would be much easier for someone who has not encountered any of the plugins before to have a guide on how to use them together.
How you set up media downloader to capture from the web browser.
Which download manager is the best?
Which video downloader combined with the download manager is the best combo?
I'm on Linux and I'm complete beginner and setting up the plugins to work together with media downloader is even more difficult.
Please include info on how to use the plugins on Linux.
Thank you!

**Comment by mhogomchungu** [comment]
> How you set up media downloader to capture from the web browser.

This is explained [here](https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#7-how-do-i-create-a-context-menu-on-chrome-or-firefox-to-open-links-in-media-downloader).

> Which download manager is the best?

It depends on what website you are trying to download from. Yt-dlp is the default but you cant use it for example to download a zip file and you will have to use either aria2c or wget for that.

> Which video downloader combined with the download manager is the best combo?

Again, it depends on what media you want to download and from what website.

> I'm on Linux and I'm complete beginner and setting up the plugins to work together with media downloader is even more difficult.

Instructions on how to install plugins are [here](https://github.com/mhogomchungu/media-downloader/wiki/Extensions). The last installed plugin will be set as the default plugin.

**Comment by formlessdao** [comment]
And how do I install it on Fedora properly?
You do realize that only advanced users can use most of this since you do not offer detailed guidelines even when asked for the steps, which is what I'm doing.
"It depends on what website you are trying to download from."
I agree, it depends but you need to provide the discerning info on how to choose one over the other.
How can I have multiple plugins installed and disable just a couple of them while letting only one or two enabled?
Is there a easy way to disable and enable them?
If you do not want to write then make a super in depth video(desktop recording) and that can be way easier than writing detailed instructions.

**Comment by mhogomchungu** [comment]
> And how do I install it on Fedora properly?

Install what?

If you want to use Media Downloader with Fedora then the best thing to do is to make a package request and ask for media downloader to be included in the Fedora official repositories.

Second best thing if you want to use it now, then there is a link in the project front page that takes you to where you can find binary packages for Fedora among other distributions and the link is [here](https://software.opensuse.org//download.html?project=home%3Aobs_mhogomchungu&package=media-downloader).

Third best thing is to build from source code and instructions on how to do that are in the front page and are  [here](https://github.com/mhogomchungu/media-downloader#source-packages)

The front page also has binary packages for Windows.

What is missing here that needs to be written about?

> I agree, it depends but you need to provide the discerning info on how to choose one over the other.

You get yt-dlp by default, if you want faster downloads then i advice use yt-dlp-aria2c. 

If we look at youtube.com then there are 4 extensions that work with the website and their names are youtube-dl, yt-dlp, lux and you-get. Here, you get my preferred choice and that is yt-dlp.

Now, you want me to do the above with what list of websites?

What you are asking is not possible since there are too many "popular" websites out there.

> How can I have multiple plugins installed and disable just a couple of them while letting only one or two enabled?

You enable a plugin by installing it and you disable it by uninstalling it.

> Is there a easy way to have many of them installed simultaneously and to disable and enable them just as I want?

No, what does "disabled" mean?

> How do I configure all my downloads to only work with Aria while the identification of a video on some website is done with another plugin that supports that website?

When in a tab of your choice, set engine name to  "Aria" and "Aria" will be used for all media you entered in that tab to be downloaded.
