### ISSUE TITLE
Python virus

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#219]
Hello, i see this news : "Dozens of malicious PyPI packages targeting developers have been discovered,
These packages contain the "W4SP" malware that would steal users' data"

https://python.developpez.com/actu/338248/Des-dizaines-de-paquets-PyPI-malveillants-ciblant-les-developpeurs-ont-ete-decouverts-ces-paquets-contiennent-le-logiciel-malveillant-W4SP-qui-volerait-les-donnees-des-utilisateurs/

it seems that our  beloved Media-Downloader use python , we hope there is no infection with this malware :)

**Comment by mhogomchungu** [comment]
Media Downloader in written in C++ and uses Qt GUI framework that is also
written in C++..

On windows, it bundles official python interpreter from official python
website.

All python programs Media Downloader downloads because user requested them
when they install an extension are downloaded from official GitHub
repositories.

Media Downloader does not use PyPI packages and hence is not affected by
its issues.
