### ISSUE TITLE
Exe or zip ?

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#225]
Hello, I was preparing to download the new beautiful version of the awesome media-downloader when I notice that the exe version MediaDownloader-2.7.0.setup.exe 49.6 MB is smaller in size than the zip version MediaDownloader-2.7.0.zip 70.1 MB! !

I thought that the exe version is the best version and i alwayas download the exe version, but there, since the size of exe version is lower than the zip version,  I think that the zip version probably contains essential elements that the exe version does not contain? what is the best version that you advise us to download and use please?

**Comment by mhogomchungu** [comment]
1, download MediaDownloader-2.7.0.setup.exe and install it.
2. Go to "C:/Program Files (x86)" folder and then zip the Media Downloader file and your zipped file will be 70MB big.
3. The only difference between extracted Media Downloader folder of a zipped version and installer version is the presence of empty folder named "local" in the zipped version and you can convert one version to the other by adding or deleting this folder.
4. The difference in size of probably due to use of compression in the setup version.
