### ISSUE TITLE
Kudos and feature request - enable Add URL to List while downloads are ongoing.

### ISSUE THREAD

**Issue by linuxguy123** [mhogomchungu/media-downloader#254]
Kudos for a well written utility.   It's great it is in the Fedora repos. 

Feature request... it would be great if one could add URLs to the batch download list while URLs are being downloaded.    So if the user is downloading a large file and finds something else he wants downloaded he can add to the list without having to wait for the current list to be completed. 

Should be as easy as adding an item to TableWidget ?

**Comment by mhogomchungu** [comment]
This is a bug since controls for adding url are disabled when downloading.

Manually typing in Url is not something i expect users to do on a regular basis and preferred way is the [clipboard monitoring feature](https://github.com/mhogomchungu/media-downloader/issues/255#issuecomment-1465105730) and add url to the UI from [browser context menu](https://github.com/mhogomchungu/media-downloader/wiki/Frequently-Asked-Questions#7-how-do-i-create-a-context-menu-on-chrome-or-firefox-to-open-links-in-media-downloader).

**Comment by mhogomchungu** [comment]
This is done.
