### ISSUE TITLE
aria2 [SocketCore.cc:1018] errorCode=1 SSL/TLS handshake failure

### ISSUE THREAD

**Issue by zinalili** [mhogomchungu/media-downloader#285]
I can't download using aria2 because of the error "[SocketCore.cc:1018] errorCode=1 SSL/TLS handshake failure"
My firewall says that "lsass.exe" is being blocked 
![Clipboard01](https://github.com/mhogomchungu/media-downloader/assets/13087157/3b1e8410-ad4b-44c6-8573-9d2ab4a77556)
Other GUIs to aria2 do not ask me to allow Internet access to lsass.exe and they download files just fine.

**Comment by mhogomchungu** [comment]
I can not reproduce this. those other GUI use a bundled version of aria2c?

Try to replace bundled version of aria2c in MD with another one and see if it makes a difference.

**Comment by zinalili** [comment]
MD with this other GUI's aria failed to download because lsass.exe coudn't connect
This other GUI with MD's aria downloaded successfully.

**Comment by mhogomchungu** [comment]
So the problem is most likely caused by a firewall of some sort in your computer blocking aria2c's connections when used with MD..

Perhaps a solution is whitelisting MD somewhere in your system to allow it and processes it starts to access the internet.

I do not think there is anything i can do with this one and thanks for your report and your investigation.
