### ISSUE TITLE
yt-dlp 2023.06.22 does not show japanese characters when use %(uploader)s

### ISSUE THREAD

**Issue by candrapersada** [mhogomchungu/media-downloader#292]
Why when using `%(uploader)s` does not show japanese characters 
https://youtu.be/dnM7tb4q6sY

**Comment by mhogomchungu** [comment]
There are no Japanese character in the url's uploader name.

```
yt-dlp --print "%(uploader)s" https://youtu.be/dnM7tb4q6sY
Neste Games
```
![Screenshot_20230703_131708](https://github.com/mhogomchungu/media-downloader/assets/3496115/48ffe168-2942-4494-82aa-74a8c0ddef71)

**Comment by candrapersada** [comment]
but yt-dlp 2023.03.04
![image](https://github.com/mhogomchungu/media-downloader/assets/36833664/559c8024-0c14-4100-a8a9-9bc21c51f8c2)

**Comment by mhogomchungu** [comment]
I can reproduce the issue and this issue is with yt-dlp and has nothing to do with Media Downloader and therefore does not belong here.

I have posted a comment about this issue in [r/youtube-dl](https://www.reddit.com/r/youtubedl/comments/14fxqlm/ytdlp_release_20230622/jqjiddo/) and hopefully developer of yt-dlp will see it and respond.

**Comment by mhogomchungu** [comment]
This change of behavior is on yt-dlp and there is nothing i can do in Media Downloader to fix it.

I have looed in yt-dlp documentation and did not see any option to change language so i do not think there is a way to get back the old behavior.
