### ISSUE TITLE
please add support for a checkbox setting to auto start downloads when added respecting maximum concurrent download limits already existing

### ISSUE THREAD

**Issue by deee167** [mhogomchungu/media-downloader#312]
please add support for a checkbox setting to auto start downloads when added respecting maximum concurrent download limits already existing

**Comment by deee167** [comment]
any update on this?

**Comment by mhogomchungu** [comment]
1. There is no room for another checkbox.

2. This option makes most sense in the playlist downloader tab because it
could take a very long time to load the entire playlist.

3.  It is possible to add new entries while downloading in batch downloader
tab and newer entries will be downloaded when current ones finish. You can
get the behavior you want by adding the first entry, start downloading it
and then adding the rest of the entries.

4. This tool is now entering maturity stage where I will not do fundamental
changes in it's architecture. This feature will require a fundamental
change in how entries are getting downloaded or will require a parallel
architecture to be used. Step 3 above is done by restarting the download
process when the last download finish and the UI has newer enteries to be
downloaded.

**Comment by deee167** [comment]
1) what are you talking about, it's an app, you can add the ability to resize the window (crazy that you can't right now as it is, its' a basic feature), and you can add a scroll bar to the options, or add more tabs for options.  I don't understand where you are coming from that there is no room.  There are so many ways that every app in existence pretty much does this.

2) that's not where I need it, so that won't help me.  I need it where I mentioned.  It should be a global option that applies to all batch downloader tasks

3) that doesn't work,  I have 4 concurrent downloads going and new downloads don't start if there is only one active download going and you add more

4) I don't understand how this requires a fundamental architecture change.  You said when a download finishes, it checks and starts others.  Just put in code when a url is added, check how many downloads are active and if less than the limit, and there are not started downloads start enough to reach the limit.

You should consider an architecture change as it seems you have a lot of strange limitations.  Do you have unit tests to verify the behaviour that you could just re-run?  Anyway, you don't need to change the architecture, but the limitations you mentioned seem very strange to me.  At least add support for this item.  I don't see how it could be complicated based on what we discussed.

Thanks :)

**Comment by mhogomchungu** [comment]
Perhaps i should stop explaining myself because my explanations seems to generate more explanations.

Let me summaries my position

This is a nice feature to have and i would like to have it especially for playlist downloader and the reason why it is not there yet is because i do not feel like doing it as it requires revisiting long settled code paths.

Will keep this feature request open but dont expect anything anytime soon.

**Comment by deee167** [comment]
thanks for the addition of hiding completed downloads in the latest version.

Please add support for this item.  I would love to have this feature.

**Comment by deee167** [comment]
Could you add support for this please?

**Comment by deee167** [comment]
Sorry, I really don't mean to bother you but this feature is really useful to me.  If you could find some time to implement this, that would be great.

Thanks for making this app.  Hope you have a great day.

**Comment by mhogomchungu** [comment]
No checkbox for now in the UI.

When a new version is out, start it and then close it and then look in the settings file and you will see an option named "AutoDownloadWhenAddedInBatchDownloader", set its value to true and start again media downloader.
