### ISSUE TITLE
Add nonfree builds of FFmpeg 

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#329]
Hello, using nonfree builds of FFmpeg may fix some bugs....

https://github.com/AnimMouse/ffmpeg-autobuild

and "In many countries, algorithms cannot be patented, FFmpeg can therefore not violate any patent law by implementing patented algorithms in these countries."

http://trac.ffmpeg.org/ticket/65

We hope there will be special version of Media_Downloader who uses this nonfree builds of FFmpeg ! Thank you !

**Comment by mhogomchungu** [comment]
I get Window's binaries from [here.](https://github.com/yt-dlp/FFmpeg-Builds)

Best thing about these builds is that they are made by yt-dlp and they are the best for Media Downloader because it primarily work for yt-dlp.

They do not include non GPL builds so i can not use them.

Using builds from other places risks things breaking in ways they do support and i do not want to risk it.

**Comment by trimechee** [comment]
Interesting, we understand , thank you :)
