### ISSUE TITLE
The LOG window is displaying inaccurate information.

### ISSUE THREAD

**Issue by tusharchopra07** [mhogomchungu/media-downloader#344]
It is unclear whether there was a bug or not, but I experienced a problem where the command I entered in the preset field or saved as a preset did not display correctly in the terminal window.

![presets issue](https://github.com/mhogomchungu/media-downloader/assets/128215171/d3c9913f-d1fc-471d-899e-8122ae89aabd)

My input was limited to --list-formats, however, the TERMINAL LOG windows presents various arguments instead of solely showing --list-formats.

**Comment by mhogomchungu** [comment]
That input field is for adding "downloading options" and your "--list-formats" option gets ignored

If you want to see available formats then look at the UI again and click the button named "Get List"

**Comment by tusharchopra07** [comment]
It was just to show 
I have added the commands in Saved Prestes also but still..... It shows different arguments in screen 
Wait I'll show you a ScreenRecord

**Comment by mhogomchungu** [comment]
look closer at the UI and you will see your ```--list-formats``` option is included and you are not getting what you expect because yt-dlp ignored it probably because it paid attention to ```-f``` option.

Media Downloader has its own options it passes to yt-dlp and user options are added to Media Downloader options before all of them are sent to yt-dlp and not what you expect where only user options are used if present. What you expect will not work because wanting to add one option will require adding all expected options.
