### ISSUE TITLE
[Extension Error] Installing Gallery-dl extension

### ISSUE THREAD

**Issue by Carathon** [mhogomchungu/media-downloader#370]
I am not able to install gallery-dl extension successfully although it is installed on my system.

![Bildschirmfoto zu 2024-01-24 16-34-13](https://github.com/mhogomchungu/media-downloader/assets/98384888/7bf5c332-7b85-4092-adeb-a832fbc4c080)

![Bildschirmfoto zu 2024-01-24 16-38-10](https://github.com/mhogomchungu/media-downloader/assets/98384888/31a7709d-805a-4992-a60e-ca9dfa8c8aad)

System: Linux Mint Virginia 21.3

**Comment by mhogomchungu** [comment]
Open the terminal, run the following command and post here its output
```
/home/kev/.local/share/media-downloader/bin/gallery-dl.bin --version
```

**Comment by mhogomchungu** [comment]
The UI now shows as seen in the image below what error is produced when Media Downloader fails to get info about a backend.

Latest version of gallery-dl does not work in my system and i suspect you are getting the same error.

There is nothing i can do about this error since the problem is between gallery-dl and your system.

![Screenshot_20240125_165822](https://github.com/mhogomchungu/media-downloader/assets/3496115/e79a8ad5-275c-4a94-b73e-953e020fc7be)

**Comment by Carathon** [comment]
kev@kev-ThinkPad-T450s:~$ /home/kev/.local/share/media-downloader/bin/gallery-dl.bin --version
[3308] Error loading Python lib '/tmp/_MEIn0SLwa/libpython3.11.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/_MEIn0SLwa/libpython3.11.so.1.0)

this was the output
