### ISSUE TITLE
Add new optional extension to fix cookies problems

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#374]
Hello, chromium web browsers are constantly evolving and the cookie problem may return again..... I propose that M-D adds new optional extension based on these open source tools to solve these complex cookie issues and M-D will ask the user to accept the possible risk, thank you !

otherwise I think it is necessary for M-D to add this preset by default: " --cookies-from-browser firefox" because Firefox seems not to be affected by cookie problems, or add by default this preset "yt-dlp --cookies-from-browser chrome --cookies cookies.txt" that seems to fix these cookies problems ! thanks !

https://github.com/seproDev/yt-dlp-ChromeCookieUnlock
https://gist.github.com/csm10495/e89e660ffee0030e8ef410b793ad6a7e
https://github.com/kairi003/Get-cookies.txt-LOCALLY
https://github.com/thewh1teagle/rookie
https://www.reddit.com/r/youtubedl/comments/1ag73tz/linkedin_learning_download_issue/koexo5i/?context=3
https://www.reddit.com/r/youtubedl/comments/ou1mtk/ytdlp_how_i_use_cookies_from_browser/
https://github.com/yt-dlp/yt-dlp/issues/3766
https://github.com/yt-dlp/yt-dlp/issues/7271
https://github.com/yt-dlp/yt-dlp#installing-plugins
https://github.com/yt-dlp/yt-dlp#plugins

EDIT : may be it can help to add it as "extensions"  : https://github.com/zaidka/cliget

**Comment by mhogomchungu** [comment]
Cookies contain sensitive information and i do not think its wise to automatically add them by default.

Adding "--cookies-from-browser" option by default is also problematic because there are many web browsers and there is no way of knowing which ones a user prefer to be set.

The fix for the cookie problem should be solved at the tool  level that does the downloading and not Media Downloader.

**Comment by trimechee** [comment]
Very interesting , we understand, thank you :)
