### ISSUE TITLE
How to download videos in a playlist in reverse order?

### ISSUE THREAD

**Issue by RevanMardagh** [mhogomchungu/media-downloader#389]
I have used --playlist-reverse in download options and in engines default options but doesnt work. Am I missing something?

**Comment by mhogomchungu** [comment]
Yt-dlp playlist options do not work because Media Downloader calls yt-dlp
with each entry in the UI as an independent entity.

The only way to support this option is inside Media Downloader and I think
the best way to do it is to add a context menu option to reverse the
entries in the UI or to add entries in the UI in a reverse order.

**Comment by RevanMardagh** [comment]
Alright, thanks for the response. :)
Will be checking release changelogs every time 😉

**Comment by mhogomchungu** [comment]
```--playlist-reverse``` option is now supported and you can use a version with the support if you are using windows by downloading a git version from below link.

https://github.com/mhogomchungu/media-downloader-git/releases

**Comment by RevanMardagh** [comment]
will it be added as an official release?

**Comment by mhogomchungu** [comment]
The next version will be released on May 1st, 2024.

You can wait until then to use the functionality with a new version or you can use the functionality now by using a git version, the choice is yours.

**Comment by RevanMardagh** [comment]
Thanks! :D

**Comment by mhogomchungu** [comment]
New version is out

https://github.com/mhogomchungu/media-downloader/releases/tag/4.6.0
