### ISSUE TITLE
Misspelling in one of the preset options.

### ISSUE THREAD

**Issue by kolbdog323** [mhogomchungu/media-downloader#394]
Just letting you know you have this spelled wrong Best Audio and Video for MPV. It's suppoed to be MKV not MPV.

**Comment by mhogomchungu** [comment]
Can you post a screenshot that shows the misspelling?

**Comment by kolbdog323** [comment]
Here you go:

![for online](https://github.com/mhogomchungu/media-downloader/assets/161794176/b822b90a-7acb-42ff-be50-db6bff2e7275)

**Comment by mhogomchungu** [comment]
You must have added the option yourself, the last part of the code that initially populate the list is below and the problematic entry is not in the code.

https://github.com/mhogomchungu/media-downloader/blob/513b8bc56870865d57696fe093ebedba9f473009/src/configure.cpp#L1316-L1335

**Comment by kolbdog323** [comment]
Nope i have never touched the code once. I wouldn't even know where to fix it manually.

**Comment by kolbdog323** [comment]
I found it. Maybe you can add that option in for people who want the best mkv since a lot of times that file size is smaller then the mp4 format.

**Comment by mhogomchungu** [comment]
The UI place to add options to the list is at "Configure Tab->Preset Options subtab".

Either you or somebody else added the options and mistyped the entry in the "Ui Name" text field because Media Downloader adds no such entry by itself.

The default list is already too long already and i do not think this addition will add too much value and will just open up a door for others to ask for other default entries that downloads webm by default.

Webm videos are discouraged by default in Media Downloader because they do not work everywhere.
