### ISSUE TITLE
UI - Resolution Issue - Can press buttons

### ISSUE THREAD

**Issue by martiniturbide** [mhogomchungu/media-downloader#425]
Hello

I think this may be very simple but I don't know how to fix it.

In Windows 11 on this machine (1920x1080), I see the Media downloader like this:
<img width="960" alt="MediaD" src="https://github.com/mhogomchungu/media-downloader/assets/498092/fc79cabb-3eaa-472b-8e1c-1763fe964158">

I can not resize the windows, or press the buttons. I guess it is something wrong I have on Windows. My workarround is to hide the taskbar, but I want something that fix the issue.
Please let me know any tips.

Regards

**Comment by mhogomchungu** [comment]
By design, the app window can not be resized but can be scaled up or down by changing a settings option. This UI option to scale the UI was removed in this version 4.8.0 because it was not possible to reset the UI if a user used a wrong option causing the UI to be too big or too small.

To scale down the UI, do the following:-

1. Close Media Downloader.
2. Go to a folder at ```C:/Users/MI/AppData/Roaming/media-downloader/settings```.
3. Open the settings file inside the folder above with a text editor.
4. Look for the option named ```EnabledHighDpiScalingFactor``` and change its value to ```0.8```.
5. Close the text editor and restart Media Downloader and check the UI has the smaller size you want. Repeat above steps changing scale factor until the UI has the size that works best for you.

**Comment by martiniturbide** [comment]
Thanks for the feedback.

It also worked for me to add a Windows environment variable for Qt.
- QT_AUTO_SCREEN_SCALE_FACTOR = 0

Thanks for the information. I will try it it too.
Regards

**Comment by mhogomchungu** [comment]
Glad you found a working solution.
