### ISSUE TITLE
Are you a bot?

### ISSUE THREAD

**Issue by jpalcantara** [mhogomchungu/media-downloader#436]
It is asking to login

ERROR: [youtube] qdo5l0R1lX4: Sign in to confirm you’re not a bot. This helps protect our community. Learn more
[media-downloader] Download Failed(ErrorCode=1)

Is there a solution?

**Comment by mhogomchungu** [comment]
If you are downloading too much and too soon then try to add delays between your downloading.

If you are using VPN then try using a different one.

Another suggestion is to tell yt-dlp to access your web browser when its logged in to youtube but some are advising against doing this.

This issue is tracked upstream [here](https://github.com/yt-dlp/yt-dlp/issues/10128#issuecomment-2155037169) and there is nothing i can do in Media Downloader to work around it.
