### ISSUE TITLE
svtplay-dl seems to unpack in wrong path

### ISSUE THREAD

**Issue by TobbeLino** [mhogomchungu/media-downloader#443]
Hi
I had an older version of svtplay-dl installed (4.69), Media Downloader detected it and downloaded and unpacked latest 4.97.1 (and everything was working fine). But next time I started Media Downloader, it would again detect svtplay-dl v 4.69 and update it to 4.97.1.
On every restart...

When checking what's actually in the folders, I found that in "C:\Users\<user>\AppData\Roaming\media-downloader\bin" there was "svtplay-dl.exe" version 4.69, but Media Downloader would unpack 4.97.1 in a subfolder "C:\Users\<user>\AppData\Roaming\media-downloader\bin\svtplay-dl". So I had two versions installed, and on every restart, Media Downloader detected one of them and updated the other :)

I could manually resolve this by moving everything in the "svtplay-dl"-folder to its parent folder (overwriting v 4.69).
So it seems that svtplay-dl has added an extra folder level in its artifact...

**Comment by mhogomchungu** [comment]
1. In the top folder, you have version 4.69 of svtplay-dl and this version was released on Dec 12, 2023.
2. Media Downloader started auto downloading svtplay-dl in version 4.5.0 and this version was released in April 1st, 2024.
3. Media Downloader downloads svtplay-dl to a subfolder named "svtplay-dl" and this is the proper place.

Can you check when version 4.69 was installed by checking creation dates of its files and folders?

I suspect at some point in the past, you manually installed svtplay-dl version 4.69 in the "bin" top folder(wrong location) and this version is confusing Media Downloader because it is seen first when Media Downloader is checking for updates.

**Comment by TobbeLino** [comment]
Thanks for your response!
Yes, it's possible that I installed svtplay-dl manually some time in the past - can't remember.

Sorry, I can't check creation date of v 4.69 because I deleted these files from the top folder.

**Comment by mhogomchungu** [comment]
I have solved this problem by searching last for binaries the top folder.
