### ISSUE TITLE
Media Downloader was stuck in task manger and changed to App Data Path to "/AppData/Roaming"

### ISSUE THREAD

**Issue by metapea** [mhogomchungu/media-downloader#446]
When updating from a portable version of media downloader to 5.1.0, it got stuck when loading the program after the update and i had to end task. 
It keep doing the same thing until i opened with admin then it worked but the "App Data Path" was changed to "/AppData/Roaming" afterwards like if it was installed. 
Is there a way to change "App Data Path"?

**Comment by mhogomchungu** [comment]
1. What version of Windows are you using.
2. Where is the portable version located in your computer.

You are using a portable version and hence the "app data path" is constructed at startup time and is dependent on where "media-downloader.exe" is.

Paths on portable version are expected to change as users move from a computer to another.

**Comment by metapea** [comment]
> What version of Windows are you using

7, And it always worked regardless.

> Where is the portable version located in your computer.

One the Non-`C:` drives i have. For example the _App Data Path_ went from: `X:/folder/media-downloader.exe` to `C:/users/X/AppData/Roaming/media-downloader`

> constructed at startup time

It's usually the case in previous versions where it takes longer then usual to boot up, but i might've mistake it as being stuck due to seeing no progress and hanging on the task manger with the same K-bits longer then usual or it actually was stuck on constructing at the startup and after ending the task two times and one startup with admin, it defaulted to "AppData/Roaming".

Media Downloader works fine now and downloads are ok, but the "App Data Path" is still on the wrong folder, all of my past settings are gone since "App Data Path" restarted to default settings in the "AppData/Roaming" folder of  "C:" and there no option in the settings to change the "App Data Path".

**Comment by metapea** [comment]
Update: After clicking on "media-downloader.exe" in "X:\folder\local\update", at first did nothing at first then it open to a restarted media-downloader with the dark ui, but after closing and click on the main "media-downloader.exe",  it fixed the "App Data Path" somehow. Now it's in the same local folder.

**Comment by mhogomchungu** [comment]
Now that it is working, are you running version 5.1.0?

On Windows and when running in portable mode, updates are installed at "$APP_DATA_PATH/local/update_new"

On startup after an update, the following steps are taken when running portable version:-

1. Check if a folder at "$APP_DATA_PATH/local/update_new" exists.
2. If it does then delete a folder at "$APP_DATA_PATH/local/update".
3. Rename "$APP_DATA_PATH/local/update_new" to "$APP_DATA_PATH/local/update".
4. Run "$APP_DATA_PATH/local/update/media-downloader.exe" with data path of "$APP_DATA_PATH".

I suspect the delay you see on the first start after an update is due to step 2 above.

The code path that decides if you are running a portable version or not and sets "app data path" accordingly is at the end of this post.

Media Downloader though you were running an installed version because a folder named "local" that is next to "media-downloader.exe" could not be found(check at line 1162 failed). Why? i Do not know. If the systems the folder does not exists then i think its best to assume it does not exist.

https://github.com/mhogomchungu/media-downloader/blob/30ffd4a304a414dc3ff00fc5c9298892de5ae0f0/src/settings.cpp#L1155-L1172

**Comment by metapea** [comment]
> Now that it is working, are you running version 5.1.0?

It says Version: 4.9.0/5.1.0 now, and it was downloading 5.1.0

**Comment by mhogomchungu** [comment]
And the UI? Its back to normal or is it still dark?

Will leave this one open until i change how new version are started the first time and how to delete the old version.

**Comment by metapea** [comment]
> And the UI? Its back to normal or is it still dark?
> "it fixed the "App Data Path" somehow"

It fixed the program/main .exe/folder with all my settings and it has the new dark/blue UI. It didn't reset to white like with the C: folder

**Comment by mhogomchungu** [comment]
If your desktop is not using a dark theme then it is a bug for Media Downloader to default to a dark theme.

**Comment by metapea** [comment]
> If your desktop is not using a dark theme then it is a bug for Media Downloader to default to a dark theme.

Like i said everything fixed so far, when the folder path didn't work it rested to the white ui as it was set to the default, that's why i was talking about the white theme. I was using the newer dark/blue UI beforehand.

**Comment by mhogomchungu** [comment]
This is done,

On the first start after your update, there are 3 versions of Media Downloader and they were:-
1. Version 4.9.0 located at $FOLDER.
2. Version 5.0.1 located at $FOLDER/local/update.
3. Version 5.1.0 located at $FOLDER/local/update_new.

The old behavior did the following:-

1. Version 4.9.0 deletes folder "$FOLDER/local/update".
2. Version 4.9.0 renames folder "$FOLDER/local/update_new" to "$FOLDER/local/update".
3. Version 4.9.0 starts version 5.1.0 now located at "$FOLDER/local/update".

New behavior starting with the next version will be as following keeping the same versions as above for simplicity:-

1. Version 4.9.0 renames "$FOLDER/local/update". to "$FOLDER/local/update.old".
2. Version 4.9.0 renames folder "$FOLDER/local/update_new" to "$FOLDER/local/update".
3. Version 4.9.0 starts version 5.1.0 now located at "$FOLDER/local/update".
4. Version 5.1.0 deletes "$FOLDER/local/update.old" after it is done starting up and is waiting for user inputs.

**Comment by metapea** [comment]
Thanks
