### ISSUE TITLE
When I scan it on Virtus Total it tells me that there is a virus

### ISSUE THREAD

**Issue by ezhupa99** [mhogomchungu/media-downloader#450]
Please check it out why does it show like this?

![image](https://github.com/user-attachments/assets/01a55ede-6724-47d6-b491-88a0dd1cba35)

**Comment by mhogomchungu** [comment]
It is a false positive because this tool does not have any virus in it or any malicious code.

I do not use Windows, i have windows installed in VirtualBox so that i can develop for window and these reports i am seeing about my projects being identified as viruses make me wonder about computing life windows users have.

There is nothing i can do here other that to say to ignore that warning.
