### ISSUE TITLE
Feature Request: Support subtitles

### ISSUE THREAD

**Issue by Stefanoko** [mhogomchungu/media-downloader#454]
It were great if an available subtitle file could be downloaded along with the video, in one go.

An elaborate GUI is not needed, imo, it would suffice to be able to specify the language, like say "fr" for French, to download the corresponding .fr.srt file together with the video. If unavailable, the program would then look for an auto-generated subtitle file  (.fr-asr.srt). Or simply download both, they're small files after all. 

If nothing can be found, just proceed without further ado, downloading the video only.

**Comment by mhogomchungu** [comment]
"Download Options" text field is there "front and center" so that you can easily customize downloading options to your liking.

All options that deal with subtitles are [here](https://github.com/yt-dlp/yt-dlp?tab=readme-ov-file#subtitle-options).

It looks like the options you want to add are:
```
--sub-format srt --sub-langs fr 
```

Closing this one but feel free to continue commenting.
