### ISSUE TITLE
Orielly

### ISSUE THREAD

**Issue by OpenDirr** [mhogomchungu/media-downloader#46]
Whenever I Input credentials in the json file it just decides not not to download the file from the repo some help would be great, whenever I add credentials doesn't install plugin

**Comment by mhogomchungu** [comment]
I can not make sense of what you wrote, can you please rephrase your problem.

In the mean time, i will try to download a book again and see if i can reproduce the problem.

**Comment by OpenDirr** [comment]
> I can not make sense of what you wrote, can you please rephrase your problem.
> 
> In the mean time, i will try to download a book again and see if i can reproduce the problem.

apologize, What I was trying to say is that I'm not able to download books whenever I download the config json file and input my credentials it doesn't add the plugin to the downloader but whenever I leave it unedited it works fine and installs

**Comment by mhogomchungu** [comment]
I think the plugin is not added when you add your credentials because the config ends up not being a valid json file and i think of two reasons why it happens:-
1. You are not properly adding the credentials and you end up corrupting the file.
2. Your credentials contain invalid json characters and they end up corrupting the file.

Will add a log entry that says why a config file failed to be loaded.
