### ISSUE TITLE
feature requests: be able to redownload the same video

### ISSUE THREAD

**Issue by memebl14** [mhogomchungu/media-downloader#470]
when I download a part of a video, when I try to download another part of the same video later, the download is canceled because I've already downloaded that video before
![image](https://github.com/user-attachments/assets/bd711aec-de01-4308-9e13-92143153265e)
I can only download it again if I move the file to another folder

-----------

another feature I'd find interesting is to have the option to recode the video to mp4 when it's not downloaded in that format (like 1440p youtube videos), it's not very practical to always have to type “--recode mp4”.

**Comment by mhogomchungu** [comment]
Its not possible to know in advance what filename yt-dlp is going to use so Media Downloader can not preemptively rename/move the already existing file before yt-dlp detects it. The library tab has an option to rename downloaded files and you use this feature as a quick work around, just click an entry you want to rename and then select "rename"

To work around retyping "--recode mp4", you can do the following:-

1. Add a "preset option" that has the option(Configure tab->Preset Options).
2. Add a custom engine's default options and add "--recode mp4" to the list of options(Configure->engines's default options).

You can then click to select the option instead of typing it all the time.

**Comment by memebl14** [comment]
ok, thanks
I had this doubt because other YT-DLP GUIs can download the same video other times, but thanks for answering

**Comment by mhogomchungu** [comment]
Please name them and post links to where i can find them and confirm what you are saying.

**Comment by memebl14** [comment]
test this one: https://github.com/aandrew-me/ytdownloader
this one allows you to download the same video, but if the file name is the same, the new file will replace the old one. One way to get around this in this app is by downloading only part of the video, so the downloaded part will be put at the end of the file name, example “[00#00-10#00]”
![image](https://github.com/user-attachments/assets/6a9b86b6-8b13-479d-a523-ede9aa414b7c)

----------

and this one: https://github.com/onionware-github/OnionMedia
this other app can download the video again without any problems, and when the file names are the same it just adds “_2” to the end of the file name.
![image](https://github.com/user-attachments/assets/ebe8b493-f756-44cb-9ef4-8562a56a7bf5)

**Comment by mhogomchungu** [comment]
It is not possible to predict in advance the final file name with yt-dlp and what you are asking is not possible.
