### ISSUE TITLE
The compatibility problematic of yt-dlp-ffmpeg and yt-dlp-aria2c in my windows 7 os 32 bits

### ISSUE THREAD

**Issue by trimechee** [mhogomchungu/media-downloader#479]
Hi, so i need sometimes to use yt-dlp-ffmpeg and yt-dlp-aria2c because speed dowload is throttled in youtube and dailymotion when using yt-dlp , but i remember i tried to install ffmpeg 32 bits for windws 7 os but ffmpeg does not support windows 7 os anymore, on the other hand aria2 has a 32 bits version but i don't know if it is compatible with windows 7 OS.....

so my question please is: does Media-Downloader officially support yt-dlp-ffmpeg and yt-dlp-aria2 for windows 7 os 32 bits ? and how does M-D use ffmpeg when ffmpeg does not support windows 7 os anymore? does M-D use a legacy version of ffmpeg in windows 7 os ?

**Comment by mhogomchungu** [comment]
I do not have Windows7 system so i can not test. I only have 64 bit windows 10.

I support windows7 32 bit by choosing to use programs that work on 32 bit Windows7 and these programs are:-
1. Qt 5.15.
2. Python 3.8.10.
3. Aria2 1.37.0

I bundle ffmpeg n7.0-7 because you requested the update from ffmpeg n6 i was initially bundling.  If ffmpeg n7.0-7 i am bundling does not work on 32 bit window7 then you should have reported it when i initially bundled it.
