### ISSUE TITLE
Does media-downloader support unicode in paths?

### ISSUE THREAD

**Issue by korniltsev** [mhogomchungu/media-downloader#6]
I had a tiny issue with the program. It wanted to download videos to a path in "Владимир\Desktop" folder or something and it could not download videos (hang forever). Once I changed the path to C:\youtube it started working smoothly. I wonder if  russian directory name was the problem.
It also would be nice if youtube-dl would be downloaded automatically (or with a single button click) from github .
Thanks for the project!

**Comment by mhogomchungu** [comment]
The default download path on Windows is set here[1] and the documentation for QDir::homepath() is here[2]. Media downloader deals with paths using QString and it should work fine with russian paths and the path of "Владимир\Desktop" seems strange because it is not a full path to a user's profile directory.

Yes, being able to download on first run and update youtube-dl automatically is on my to do list and will probably be there with the next release.

[1] https://github.com/mhogomchungu/media-downloader/blob/ab973784bf5c811492fd2d18d2260e7539567e18/src/settings.cpp#L48

[2] https://doc.qt.io/qt-5/qdir.html#homePath

**Comment by korniltsev** [comment]
I meant it ended with "Владимир\Desktop" the full path was smth like "D:\Users\Владимир\Desktop"
I'l close since you can't reproduce.

**Comment by mhogomchungu** [comment]
More info about auto downloading of youtube-dl is here: https://github.com/mhogomchungu/media-downloader/issues/7

**Comment by mhogomchungu** [comment]
New version is out and it automatically download youtube-dl on first run and there is a button in the configure tab to update youtube-dl on demand.

https://github.com/mhogomchungu/media-downloader/releases/tag/1.1.0
